# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.JobPosting')),
            ],
        ),
    ]
