# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_referral_referral_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('ACCEPTED', 'ACCPTED')], default='WAITING', max_length=10),
        ),
    ]
